# -*- coding: utf-8 -*-
"""projeto_pressoes_temperaturas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q6XzZPID-Z-D5pxJdMNc0SyvhHHfsNFX
"""

pressoes = [100, 120, 140, 160, 180]
temperaturas = [20, 25, 0, 35, 40]


def divide_colunas(lista_1: list, lista_2: list) -> list:
  try:
    if len(lista_1) != len(lista_2):
      raise ValueError('As listas precisam ter o mesmo tamanho!')

    resultado = [round(a / b, 2) for a, b in zip(lista_1, lista_2)]
  except ValueError as e:
    print(e)
  except ZeroDivisionError as e:
    print(f'{e}: A 2° lista não pode possuir um valor igual a 0')
  else:
    return resultado


divide_colunas(pressoes, temperaturas)